#!/usr/bin/env python3
"""
refresh_cloud_ranges.py — fetch official published cloud IP ranges → cloud_ip_ranges.json.

4.7 ruling P3 (2026-07-24): the scan-time cloud-edge BACKSTOP (cloud_ip_check.py) matches
resolved IPs against published cloud CIDRs. This builder fetches the authoritative feeds and
writes scripts/asm/cloud_ip_ranges.json. Runs ON A RUNNER (which can reach the feeds) via a
weekly PR-reviewed workflow (refresh-cloud-ranges.yml) or workflow_dispatch — NOT at scan time
(no per-scan fetch latency, no runner-DNS fragility; the committed file is deterministic).

Feeds:
  gcp   https://www.gstatic.com/ipranges/cloud.json            (prefixes[].ipv4Prefix/.ipv6Prefix)
  aws   https://ip-ranges.amazonaws.com/ip-ranges.json         (prefixes[].ip_prefix, ipv6_prefixes[])
  azure https://raw.githubusercontent.com/microsoft/azure-ip-ranges/main/ServiceTags_Public.json
        (values[].properties.addressPrefixes[])  [community mirror of the weekly service-tags file]

Safety (P3 sanity checks): if a feed fails or returns a suspiciously small set, that provider's
EXISTING committed prefixes are RETAINED (never blindly emptied). Exit non-zero only if ALL feeds
fail (so the workflow can flag it); otherwise write what we got.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

OUT = Path(__file__).resolve().parent / "cloud_ip_ranges.json"
# A provider's fetch is accepted only if it yields at least this many prefixes
# (guards against a feed returning empty/garbage and wiping good data).
MIN_PREFIXES = 20


def _get(url: str, timeout: int = 30) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": "commandsentry-asm/refresh-cloud-ranges"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8", "replace"))


def _gcp() -> list[str]:
    d = _get("https://www.gstatic.com/ipranges/cloud.json")
    out = []
    for p in d.get("prefixes", []):
        v = p.get("ipv4Prefix") or p.get("ipv6Prefix")
        if v:
            out.append(v)
    return out


def _aws() -> list[str]:
    d = _get("https://ip-ranges.amazonaws.com/ip-ranges.json")
    out = [p["ip_prefix"] for p in d.get("prefixes", []) if p.get("ip_prefix")]
    out += [p["ipv6_prefix"] for p in d.get("ipv6_prefixes", []) if p.get("ipv6_prefix")]
    return out


def _azure() -> list[str]:
    d = _get("https://raw.githubusercontent.com/microsoft/azure-ip-ranges/main/ServiceTags_Public.json")
    out: list[str] = []
    for v in d.get("values", []):
        out += (v.get("properties", {}) or {}).get("addressPrefixes", []) or []
    return out


FEEDS = {"gcp": _gcp, "aws": _aws, "azure": _azure}


def main() -> int:
    try:
        prev = json.loads(OUT.read_text())
    except Exception:
        prev = {}
    prev_prefixes = prev.get("prefixes") or {}

    prefixes: dict[str, list[str]] = {}
    versions: dict[str, str] = dict(prev.get("source_versions") or {})
    ok = 0
    for name, fn in FEEDS.items():
        try:
            got = sorted(set(fn()))
        except Exception as e:
            got = []
            print(f"[warn] {name} fetch failed: {type(e).__name__}: {e}", file=sys.stderr)
        if len(got) >= MIN_PREFIXES:
            prefixes[name] = got
            versions[name] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            ok += 1
            print(f"[ok] {name}: {len(got)} prefixes")
        else:
            # retain existing rather than wipe (P3 safety)
            if prev_prefixes.get(name):
                prefixes[name] = prev_prefixes[name]
                print(f"[keep] {name}: fetch too small ({len(got)}), retained {len(prefixes[name])} committed")
            else:
                print(f"[skip] {name}: fetch too small ({len(got)}) and nothing committed")

    doc = {
        "_comment": prev.get("_comment", "Published cloud IP ranges — backstop for cloud_ip_check.py. Machine-generated by refresh_cloud_ranges.py."),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_versions": versions,
        "sources": prev.get("sources", {}),
        "prefixes": prefixes,
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    total = sum(len(v) for v in prefixes.values())
    print(f"wrote {OUT} — {ok}/{len(FEEDS)} feeds, {total} total prefixes")
    return 0 if ok > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
